/**
 * Vendors the two UI typefaces (Cormorant Garamond, Inter — both SIL OFL)
 * into src/assets/fonts and generates src/styles/fonts.css, so the site has
 * no runtime dependency on Google Fonts. Re-run only to change weights.
 *
 *   node scripts/vendorFonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'src', 'assets', 'fonts');
const CSS_PATH = join(ROOT, 'src', 'styles', 'fonts.css');

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Inter:wght@300;400;500&display=swap';
// A modern browser UA makes the API return woff2 sources.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';
const SUBSETS = new Set(['latin', 'latin-ext']);

const css = await (await fetch(CSS_URL, { headers: { 'user-agent': UA } })).text();

// Parse "/* subset */ @font-face { ... }" blocks.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)].map(([, subset, body]) => ({
  subset,
  family: body.match(/font-family:\s*'([^']+)'/)?.[1],
  style: body.match(/font-style:\s*(\w+)/)?.[1],
  weight: body.match(/font-weight:\s*(\d+)/)?.[1],
  url: body.match(/url\((https:[^)]+\.woff2)\)/)?.[1],
  range: body.match(/unicode-range:\s*([^;]+);/)?.[1],
}));

const wanted = blocks.filter((b) => SUBSETS.has(b.subset) && b.url);
if (!wanted.length) throw new Error('No font-face blocks parsed — Google Fonts markup may have changed.');

mkdirSync(FONT_DIR, { recursive: true });
const rules = [];
for (const b of wanted) {
  const slug = `${b.family.toLowerCase().replace(/ /g, '-')}-${b.weight}${b.style === 'italic' ? '-italic' : ''}-${b.subset}.woff2`;
  const buf = Buffer.from(await (await fetch(b.url, { headers: { 'user-agent': UA } })).arrayBuffer());
  writeFileSync(join(FONT_DIR, slug), buf);
  console.log(`${slug}  ${(buf.length / 1024).toFixed(0)} KB`);
  rules.push(
    `/* ${b.subset} */\n@font-face {\n  font-family: '${b.family}';\n  font-style: ${b.style};\n  font-weight: ${b.weight};\n  font-display: swap;\n  src: url('../assets/fonts/${slug}') format('woff2');\n  unicode-range: ${b.range};\n}`,
  );
}

writeFileSync(
  CSS_PATH,
  `/* Self-hosted typefaces (SIL Open Font License) — generated by scripts/vendorFonts.mjs. Do not edit by hand. */\n\n${rules.join('\n\n')}\n`,
);
console.log(`\nWrote ${wanted.length} faces → src/assets/fonts + src/styles/fonts.css`);
