/** Shapes of the static data cache generated by scripts/fetchWikiData.mjs */

export interface Period {
  id: string;
  name: string;
  start: number;
  end: number;
  /** Vertical stagger (world units) so overlapping periods don't collide. */
  lane: number;
  wikiTitle: string;
  wikiUrl: string;
  summary: string;
}

export interface ArtistPortrait {
  src: string;
  fallback: string;
}

export interface Artist {
  id: string;
  name: string;
  wikiTitle: string;
  periodId: string;
  born: number;
  died: number | null;
  significance: string;
  qid: string | null;
  /** Wikidata short description, e.g. "French painter (1840–1926)". */
  description: string | null;
  /** Lead extract of the artist's Wikipedia article. */
  bio: string | null;
  portrait: ArtistPortrait | null;
  wikiUrl: string;
  attribution: string;
}

export interface ArtworkImage {
  /** ~1024px-wide thumb used as the in-gallery texture. */
  thumb: string;
  /** ~1600px-wide thumb used by the inspect view. */
  large: string;
  width: number;
  height: number;
  /** Wikimedia Commons file description page (attribution link). */
  filePage: string;
  license: string;
  credit: string | null;
}

export interface Artwork {
  artistId: string;
  qid: string | null;
  title: string;
  year: number | null;
  medium: string | null;
  collection: string | null;
  sitelinks: number;
  /** Lead extract of the artwork's Wikipedia article, when one exists. */
  story: string | null;
  wikiUrl: string | null;
  wikidataUrl: string | null;
  /** null = no freely-licensed image on Wikimedia Commons (rights-restricted). */
  image: ArtworkImage | null;
}
